fieldLayouts:
  ddebd0c2-f431-409c-b6f0-0c95dc61bc4c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 24ed461b-8ca8-4318-a547-c580ae6b9b24
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22c82593-5c3e-471a-a75c-af46ba3b9dfc # Profile Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37e26aa5-a64a-4c2d-8fbf-4d4265f7e557
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11606301-cb30-4c50-b455-5ead656bbcee # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd4a35ca-3b59-42b1-a33e-31d3da663989
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 24404a1e-a8e5-4a64-95aa-638b0cfd12cd
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 9ef9856c-d50d-49d9-bd1e-e029956e2342 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
