fieldLayouts:
  0c53c2d2-6cec-48f6-a492-d8e8d403eb82:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 577aac9f-b0fd-4e6d-a6b2-82e26cc5f05a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d8695b13-9305-4f11-b758-937e573eb1e2 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa97269d-162a-48c4-afc9-cd140bbd697f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6359420f-e650-4b13-a5a5-01ac0d5c1a72 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18fd64a6-5a30-419f-ba41-9e7b184ac2b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ad503b1a-8fdf-4a3b-a93c-6bdb2c823285 # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83da71e4-eb92-4b65-a747-52c479527f4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 342e9393-8067-4c94-9386-e1c541273ddb # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3a858a5-c56b-4c9f-ae38-989c7bb00c5c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ceb2d7a-7218-4ca6-838a-e98a58cc379b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 602f8f6e-5696-433b-90c2-4e597be90483
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d79c3649-544d-4d4a-b795-45a8182cb5fd
        userCondition: null
handle: post
hasTitleField: true
name: Post
section: 9420faf5-3e37-4758-8c52-354bedac7414 # Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
