columnSuffix: null
contentColumnType: string
fieldGroup: d9caefb2-0f98-44ed-9348-d6e5ecd7640f # About
handle: profilePhoto
instructions: null
name: 'Profile Photo'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:ec1487e2-3e09-4e17-85de-151fb21bf341' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ec1487e2-3e09-4e17-85de-151fb21bf341' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:ec1487e2-3e09-4e17-85de-151fb21bf341' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
