columnSuffix: null
contentColumnType: string
fieldGroup: bd585f47-3b6d-4f10-b8ea-30c76f0863f3 # Blog
handle: topics
instructions: null
name: Topics
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:5243d9e9-fe81-41ef-a875-69941c782a8e' # Topics
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
